### ISSUE TITLE
[Presentation] Why is Rust a good language for tying systems together

### ISSUE THREAD

**Issue by mxgrey** [osrf-sig-interoperability/community#3]
This proposed presentation would cover valuable features of the Rust programming language with a particular focus on how those features benefit complex system integration. There would be a high level description of the features with some example code snippets, but we would not go into enough detail to actually teach how to be a Rust programmer.

Here is a rough outline of the Rust features that would be covered:
* Memory safety
* Performance
* Clean error handling
* Robust dependency management
* Cross-platform support (Windows, MacOS, Linux, embedded systems, and even web)
* Wide availability of middleware support (e.g. REST, websockets, Zenoh, DDS, mqtt, ROS2)

We'll also be happy to field questions afterwards.

------

If you'd like us to have this presentation, please apply a 👍 emoji to this post.

**Comment by Briancbn** [comment]
Hi @mxgrey, looking forward to the talk. Just to clarify, the presentation will be on Dec 11 as stated in [discourse post](https://discourse.ros.org/t/interoperability-interest-group-december-11th-2023-advantages-of-rust-for-software-system-integration/34896), right?

In the agenda, it is listed as Dec 7 https://github.com/osrf-sig-interoperability/community/blob/main/agenda/2023-12-07

**Comment by mxgrey** [comment]
Whoops, the title had a typo in it 🤦 

The calendar link and agenda are correct: it's today, December 7.

I can only assume my fingers typed 11 because it rhymes with 7.

**Comment by Briancbn** [comment]
Thanks for the clarification on the Rust to C++,
I managed to find the following resources.

Rust CMake integration tool:
- https://github.com/corrosion-rs/corrosion

Example to generate C++ Bindings
- https://github.com/corrosion-rs/corrosion/blob/master/test/cbindgen/rust2cpp/rust/src/lib.rs

**Comment by mxgrey** [comment]
Covered on [2023-12-07](https://github.com/osrf-sig-interoperability/community/tree/main/meetings/2023-12-07)
